# see https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
  # Group all version-updates, except Gardener. Gardener should receive its own PR this way. Security updates will
  # also receive their own individual PRs
    all-dependencies:
      applies-to: "version-updates"
      patterns:
      - "*"
      exclude-patterns:
      - "github.com/gardener/gardener"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
